### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by sik103** [sik103/tphGraph2#1]
- [ ] Complete README_ja.md
- [ ] Publish README_ja.md with github pages (using /docs/index.md)
- [ ] Complete setup.py which sets config file for apache. 
- [ ] Check `sudo systemctl restart apache2` must be run by **root-cron** to reflect new graphs.
